/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PrivateTranslateRouteImport } from './routes/_private/translate'
import { Route as PrivateOcrRouteImport } from './routes/_private/ocr'
import { Route as PrivateDashboardRouteImport } from './routes/_private/dashboard'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as PrivateTranslateIndexRouteImport } from './routes/_private/translate.index'
import { Route as PrivateOcrIndexRouteImport } from './routes/_private/ocr.index'
import { Route as Oauth2ProviderCallbackRouteImport } from './routes/oauth2.$provider.callback'
import { Route as PrivateTranslateImportRouteImport } from './routes/_private/translate.import'
import { Route as PrivateTranslateHistoryRouteImport } from './routes/_private/translate.history'
import { Route as PrivateOcrImportRouteImport } from './routes/_private/ocr.import'
import { Route as PrivateOcrHistoryRouteImport } from './routes/_private/ocr.history'
import { Route as PrivateOcrEditRouteImport } from './routes/_private/ocr.edit'
import { Route as PrivateOcrDetailsRouteImport } from './routes/_private/ocr.details'
import { Route as PrivateTranslateHistoryIndexRouteImport } from './routes/_private/translate.history.index'
import { Route as PrivateOcrHistoryIndexRouteImport } from './routes/_private/ocr.history.index'
import { Route as PrivateTranslateHistoryIdRouteImport } from './routes/_private/translate.history.$id'
import { Route as PrivateTranslateEditIdRouteImport } from './routes/_private/translate.edit.$id'
import { Route as PrivateTranslateDetailsIdRouteImport } from './routes/_private/translate.details.$id'
import { Route as PrivateOcrHistoryIdRouteImport } from './routes/_private/ocr.history.$id'
import { Route as PrivateOcrEditIdRouteImport } from './routes/_private/ocr.edit.$id'
import { Route as PrivateOcrDetailsIdRouteImport } from './routes/_private/ocr.details.$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateTranslateRoute = PrivateTranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateOcrRoute = PrivateOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const PrivateTranslateIndexRoute = PrivateTranslateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateTranslateRoute,
} as any)
const PrivateOcrIndexRoute = PrivateOcrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateOcrRoute,
} as any)
const Oauth2ProviderCallbackRoute = Oauth2ProviderCallbackRouteImport.update({
  id: '/oauth2/$provider/callback',
  path: '/oauth2/$provider/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateTranslateImportRoute = PrivateTranslateImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => PrivateTranslateRoute,
} as any)
const PrivateTranslateHistoryRoute = PrivateTranslateHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PrivateTranslateRoute,
} as any)
const PrivateOcrImportRoute = PrivateOcrImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => PrivateOcrRoute,
} as any)
const PrivateOcrHistoryRoute = PrivateOcrHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PrivateOcrRoute,
} as any)
const PrivateOcrEditRoute = PrivateOcrEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PrivateOcrRoute,
} as any)
const PrivateOcrDetailsRoute = PrivateOcrDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => PrivateOcrRoute,
} as any)
const PrivateTranslateHistoryIndexRoute =
  PrivateTranslateHistoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateTranslateHistoryRoute,
  } as any)
const PrivateOcrHistoryIndexRoute = PrivateOcrHistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateOcrHistoryRoute,
} as any)
const PrivateTranslateHistoryIdRoute =
  PrivateTranslateHistoryIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => PrivateTranslateHistoryRoute,
  } as any)
const PrivateTranslateEditIdRoute = PrivateTranslateEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => PrivateTranslateRoute,
} as any)
const PrivateTranslateDetailsIdRoute =
  PrivateTranslateDetailsIdRouteImport.update({
    id: '/details/$id',
    path: '/details/$id',
    getParentRoute: () => PrivateTranslateRoute,
  } as any)
const PrivateOcrHistoryIdRoute = PrivateOcrHistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PrivateOcrHistoryRoute,
} as any)
const PrivateOcrEditIdRoute = PrivateOcrEditIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PrivateOcrEditRoute,
} as any)
const PrivateOcrDetailsIdRoute = PrivateOcrDetailsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PrivateOcrDetailsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof AuthSignInRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/ocr': typeof PrivateOcrRouteWithChildren
  '/translate': typeof PrivateTranslateRouteWithChildren
  '/': typeof PrivateIndexRoute
  '/ocr/details': typeof PrivateOcrDetailsRouteWithChildren
  '/ocr/edit': typeof PrivateOcrEditRouteWithChildren
  '/ocr/history': typeof PrivateOcrHistoryRouteWithChildren
  '/ocr/import': typeof PrivateOcrImportRoute
  '/translate/history': typeof PrivateTranslateHistoryRouteWithChildren
  '/translate/import': typeof PrivateTranslateImportRoute
  '/oauth2/$provider/callback': typeof Oauth2ProviderCallbackRoute
  '/ocr/': typeof PrivateOcrIndexRoute
  '/translate/': typeof PrivateTranslateIndexRoute
  '/ocr/details/$id': typeof PrivateOcrDetailsIdRoute
  '/ocr/edit/$id': typeof PrivateOcrEditIdRoute
  '/ocr/history/$id': typeof PrivateOcrHistoryIdRoute
  '/translate/details/$id': typeof PrivateTranslateDetailsIdRoute
  '/translate/edit/$id': typeof PrivateTranslateEditIdRoute
  '/translate/history/$id': typeof PrivateTranslateHistoryIdRoute
  '/ocr/history/': typeof PrivateOcrHistoryIndexRoute
  '/translate/history/': typeof PrivateTranslateHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof AuthSignInRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/': typeof PrivateIndexRoute
  '/ocr/details': typeof PrivateOcrDetailsRouteWithChildren
  '/ocr/edit': typeof PrivateOcrEditRouteWithChildren
  '/ocr/import': typeof PrivateOcrImportRoute
  '/translate/import': typeof PrivateTranslateImportRoute
  '/oauth2/$provider/callback': typeof Oauth2ProviderCallbackRoute
  '/ocr': typeof PrivateOcrIndexRoute
  '/translate': typeof PrivateTranslateIndexRoute
  '/ocr/details/$id': typeof PrivateOcrDetailsIdRoute
  '/ocr/edit/$id': typeof PrivateOcrEditIdRoute
  '/ocr/history/$id': typeof PrivateOcrHistoryIdRoute
  '/translate/details/$id': typeof PrivateTranslateDetailsIdRoute
  '/translate/edit/$id': typeof PrivateTranslateEditIdRoute
  '/translate/history/$id': typeof PrivateTranslateHistoryIdRoute
  '/ocr/history': typeof PrivateOcrHistoryIndexRoute
  '/translate/history': typeof PrivateTranslateHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_private/ocr': typeof PrivateOcrRouteWithChildren
  '/_private/translate': typeof PrivateTranslateRouteWithChildren
  '/_private/': typeof PrivateIndexRoute
  '/_private/ocr/details': typeof PrivateOcrDetailsRouteWithChildren
  '/_private/ocr/edit': typeof PrivateOcrEditRouteWithChildren
  '/_private/ocr/history': typeof PrivateOcrHistoryRouteWithChildren
  '/_private/ocr/import': typeof PrivateOcrImportRoute
  '/_private/translate/history': typeof PrivateTranslateHistoryRouteWithChildren
  '/_private/translate/import': typeof PrivateTranslateImportRoute
  '/oauth2/$provider/callback': typeof Oauth2ProviderCallbackRoute
  '/_private/ocr/': typeof PrivateOcrIndexRoute
  '/_private/translate/': typeof PrivateTranslateIndexRoute
  '/_private/ocr/details/$id': typeof PrivateOcrDetailsIdRoute
  '/_private/ocr/edit/$id': typeof PrivateOcrEditIdRoute
  '/_private/ocr/history/$id': typeof PrivateOcrHistoryIdRoute
  '/_private/translate/details/$id': typeof PrivateTranslateDetailsIdRoute
  '/_private/translate/edit/$id': typeof PrivateTranslateEditIdRoute
  '/_private/translate/history/$id': typeof PrivateTranslateHistoryIdRoute
  '/_private/ocr/history/': typeof PrivateOcrHistoryIndexRoute
  '/_private/translate/history/': typeof PrivateTranslateHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/dashboard'
    | '/ocr'
    | '/translate'
    | '/'
    | '/ocr/details'
    | '/ocr/edit'
    | '/ocr/history'
    | '/ocr/import'
    | '/translate/history'
    | '/translate/import'
    | '/oauth2/$provider/callback'
    | '/ocr/'
    | '/translate/'
    | '/ocr/details/$id'
    | '/ocr/edit/$id'
    | '/ocr/history/$id'
    | '/translate/details/$id'
    | '/translate/edit/$id'
    | '/translate/history/$id'
    | '/ocr/history/'
    | '/translate/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/dashboard'
    | '/'
    | '/ocr/details'
    | '/ocr/edit'
    | '/ocr/import'
    | '/translate/import'
    | '/oauth2/$provider/callback'
    | '/ocr'
    | '/translate'
    | '/ocr/details/$id'
    | '/ocr/edit/$id'
    | '/ocr/history/$id'
    | '/translate/details/$id'
    | '/translate/edit/$id'
    | '/translate/history/$id'
    | '/ocr/history'
    | '/translate/history'
  id:
    | '__root__'
    | '/_auth'
    | '/_private'
    | '/_public'
    | '/_auth/sign-in'
    | '/_private/dashboard'
    | '/_private/ocr'
    | '/_private/translate'
    | '/_private/'
    | '/_private/ocr/details'
    | '/_private/ocr/edit'
    | '/_private/ocr/history'
    | '/_private/ocr/import'
    | '/_private/translate/history'
    | '/_private/translate/import'
    | '/oauth2/$provider/callback'
    | '/_private/ocr/'
    | '/_private/translate/'
    | '/_private/ocr/details/$id'
    | '/_private/ocr/edit/$id'
    | '/_private/ocr/history/$id'
    | '/_private/translate/details/$id'
    | '/_private/translate/edit/$id'
    | '/_private/translate/history/$id'
    | '/_private/ocr/history/'
    | '/_private/translate/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRoute
  Oauth2ProviderCallbackRoute: typeof Oauth2ProviderCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/translate': {
      id: '/_private/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof PrivateTranslateRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/ocr': {
      id: '/_private/ocr'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof PrivateOcrRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_private/translate/': {
      id: '/_private/translate/'
      path: '/'
      fullPath: '/translate/'
      preLoaderRoute: typeof PrivateTranslateIndexRouteImport
      parentRoute: typeof PrivateTranslateRoute
    }
    '/_private/ocr/': {
      id: '/_private/ocr/'
      path: '/'
      fullPath: '/ocr/'
      preLoaderRoute: typeof PrivateOcrIndexRouteImport
      parentRoute: typeof PrivateOcrRoute
    }
    '/oauth2/$provider/callback': {
      id: '/oauth2/$provider/callback'
      path: '/oauth2/$provider/callback'
      fullPath: '/oauth2/$provider/callback'
      preLoaderRoute: typeof Oauth2ProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/translate/import': {
      id: '/_private/translate/import'
      path: '/import'
      fullPath: '/translate/import'
      preLoaderRoute: typeof PrivateTranslateImportRouteImport
      parentRoute: typeof PrivateTranslateRoute
    }
    '/_private/translate/history': {
      id: '/_private/translate/history'
      path: '/history'
      fullPath: '/translate/history'
      preLoaderRoute: typeof PrivateTranslateHistoryRouteImport
      parentRoute: typeof PrivateTranslateRoute
    }
    '/_private/ocr/import': {
      id: '/_private/ocr/import'
      path: '/import'
      fullPath: '/ocr/import'
      preLoaderRoute: typeof PrivateOcrImportRouteImport
      parentRoute: typeof PrivateOcrRoute
    }
    '/_private/ocr/history': {
      id: '/_private/ocr/history'
      path: '/history'
      fullPath: '/ocr/history'
      preLoaderRoute: typeof PrivateOcrHistoryRouteImport
      parentRoute: typeof PrivateOcrRoute
    }
    '/_private/ocr/edit': {
      id: '/_private/ocr/edit'
      path: '/edit'
      fullPath: '/ocr/edit'
      preLoaderRoute: typeof PrivateOcrEditRouteImport
      parentRoute: typeof PrivateOcrRoute
    }
    '/_private/ocr/details': {
      id: '/_private/ocr/details'
      path: '/details'
      fullPath: '/ocr/details'
      preLoaderRoute: typeof PrivateOcrDetailsRouteImport
      parentRoute: typeof PrivateOcrRoute
    }
    '/_private/translate/history/': {
      id: '/_private/translate/history/'
      path: '/'
      fullPath: '/translate/history/'
      preLoaderRoute: typeof PrivateTranslateHistoryIndexRouteImport
      parentRoute: typeof PrivateTranslateHistoryRoute
    }
    '/_private/ocr/history/': {
      id: '/_private/ocr/history/'
      path: '/'
      fullPath: '/ocr/history/'
      preLoaderRoute: typeof PrivateOcrHistoryIndexRouteImport
      parentRoute: typeof PrivateOcrHistoryRoute
    }
    '/_private/translate/history/$id': {
      id: '/_private/translate/history/$id'
      path: '/$id'
      fullPath: '/translate/history/$id'
      preLoaderRoute: typeof PrivateTranslateHistoryIdRouteImport
      parentRoute: typeof PrivateTranslateHistoryRoute
    }
    '/_private/translate/edit/$id': {
      id: '/_private/translate/edit/$id'
      path: '/edit/$id'
      fullPath: '/translate/edit/$id'
      preLoaderRoute: typeof PrivateTranslateEditIdRouteImport
      parentRoute: typeof PrivateTranslateRoute
    }
    '/_private/translate/details/$id': {
      id: '/_private/translate/details/$id'
      path: '/details/$id'
      fullPath: '/translate/details/$id'
      preLoaderRoute: typeof PrivateTranslateDetailsIdRouteImport
      parentRoute: typeof PrivateTranslateRoute
    }
    '/_private/ocr/history/$id': {
      id: '/_private/ocr/history/$id'
      path: '/$id'
      fullPath: '/ocr/history/$id'
      preLoaderRoute: typeof PrivateOcrHistoryIdRouteImport
      parentRoute: typeof PrivateOcrHistoryRoute
    }
    '/_private/ocr/edit/$id': {
      id: '/_private/ocr/edit/$id'
      path: '/$id'
      fullPath: '/ocr/edit/$id'
      preLoaderRoute: typeof PrivateOcrEditIdRouteImport
      parentRoute: typeof PrivateOcrEditRoute
    }
    '/_private/ocr/details/$id': {
      id: '/_private/ocr/details/$id'
      path: '/$id'
      fullPath: '/ocr/details/$id'
      preLoaderRoute: typeof PrivateOcrDetailsIdRouteImport
      parentRoute: typeof PrivateOcrDetailsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PrivateOcrDetailsRouteChildren {
  PrivateOcrDetailsIdRoute: typeof PrivateOcrDetailsIdRoute
}

const PrivateOcrDetailsRouteChildren: PrivateOcrDetailsRouteChildren = {
  PrivateOcrDetailsIdRoute: PrivateOcrDetailsIdRoute,
}

const PrivateOcrDetailsRouteWithChildren =
  PrivateOcrDetailsRoute._addFileChildren(PrivateOcrDetailsRouteChildren)

interface PrivateOcrEditRouteChildren {
  PrivateOcrEditIdRoute: typeof PrivateOcrEditIdRoute
}

const PrivateOcrEditRouteChildren: PrivateOcrEditRouteChildren = {
  PrivateOcrEditIdRoute: PrivateOcrEditIdRoute,
}

const PrivateOcrEditRouteWithChildren = PrivateOcrEditRoute._addFileChildren(
  PrivateOcrEditRouteChildren,
)

interface PrivateOcrHistoryRouteChildren {
  PrivateOcrHistoryIdRoute: typeof PrivateOcrHistoryIdRoute
  PrivateOcrHistoryIndexRoute: typeof PrivateOcrHistoryIndexRoute
}

const PrivateOcrHistoryRouteChildren: PrivateOcrHistoryRouteChildren = {
  PrivateOcrHistoryIdRoute: PrivateOcrHistoryIdRoute,
  PrivateOcrHistoryIndexRoute: PrivateOcrHistoryIndexRoute,
}

const PrivateOcrHistoryRouteWithChildren =
  PrivateOcrHistoryRoute._addFileChildren(PrivateOcrHistoryRouteChildren)

interface PrivateOcrRouteChildren {
  PrivateOcrDetailsRoute: typeof PrivateOcrDetailsRouteWithChildren
  PrivateOcrEditRoute: typeof PrivateOcrEditRouteWithChildren
  PrivateOcrHistoryRoute: typeof PrivateOcrHistoryRouteWithChildren
  PrivateOcrImportRoute: typeof PrivateOcrImportRoute
  PrivateOcrIndexRoute: typeof PrivateOcrIndexRoute
}

const PrivateOcrRouteChildren: PrivateOcrRouteChildren = {
  PrivateOcrDetailsRoute: PrivateOcrDetailsRouteWithChildren,
  PrivateOcrEditRoute: PrivateOcrEditRouteWithChildren,
  PrivateOcrHistoryRoute: PrivateOcrHistoryRouteWithChildren,
  PrivateOcrImportRoute: PrivateOcrImportRoute,
  PrivateOcrIndexRoute: PrivateOcrIndexRoute,
}

const PrivateOcrRouteWithChildren = PrivateOcrRoute._addFileChildren(
  PrivateOcrRouteChildren,
)

interface PrivateTranslateHistoryRouteChildren {
  PrivateTranslateHistoryIdRoute: typeof PrivateTranslateHistoryIdRoute
  PrivateTranslateHistoryIndexRoute: typeof PrivateTranslateHistoryIndexRoute
}

const PrivateTranslateHistoryRouteChildren: PrivateTranslateHistoryRouteChildren =
  {
    PrivateTranslateHistoryIdRoute: PrivateTranslateHistoryIdRoute,
    PrivateTranslateHistoryIndexRoute: PrivateTranslateHistoryIndexRoute,
  }

const PrivateTranslateHistoryRouteWithChildren =
  PrivateTranslateHistoryRoute._addFileChildren(
    PrivateTranslateHistoryRouteChildren,
  )

interface PrivateTranslateRouteChildren {
  PrivateTranslateHistoryRoute: typeof PrivateTranslateHistoryRouteWithChildren
  PrivateTranslateImportRoute: typeof PrivateTranslateImportRoute
  PrivateTranslateIndexRoute: typeof PrivateTranslateIndexRoute
  PrivateTranslateDetailsIdRoute: typeof PrivateTranslateDetailsIdRoute
  PrivateTranslateEditIdRoute: typeof PrivateTranslateEditIdRoute
}

const PrivateTranslateRouteChildren: PrivateTranslateRouteChildren = {
  PrivateTranslateHistoryRoute: PrivateTranslateHistoryRouteWithChildren,
  PrivateTranslateImportRoute: PrivateTranslateImportRoute,
  PrivateTranslateIndexRoute: PrivateTranslateIndexRoute,
  PrivateTranslateDetailsIdRoute: PrivateTranslateDetailsIdRoute,
  PrivateTranslateEditIdRoute: PrivateTranslateEditIdRoute,
}

const PrivateTranslateRouteWithChildren =
  PrivateTranslateRoute._addFileChildren(PrivateTranslateRouteChildren)

interface PrivateRouteChildren {
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivateOcrRoute: typeof PrivateOcrRouteWithChildren
  PrivateTranslateRoute: typeof PrivateTranslateRouteWithChildren
  PrivateIndexRoute: typeof PrivateIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivateOcrRoute: PrivateOcrRouteWithChildren,
  PrivateTranslateRoute: PrivateTranslateRouteWithChildren,
  PrivateIndexRoute: PrivateIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRoute,
  Oauth2ProviderCallbackRoute: Oauth2ProviderCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
